export const users = [
    {
        id: "1",
        first_name: "John",
        last_name: "Doe",
        email: "john.doe@example.com",
        phone: "+1234567890",
        role: "Admin",
        status: "Active",
    },
    {
        id: "2",
        first_name: "Jane",
        last_name: "Smith",
        email: "jane.smith@example.com",
        phone: "+1234567891",
        role: "User",
        status: "Active",
    },
    {
        id: "3",
        first_name: "Mike",
        last_name: "Johnson",
        email: "mike.johnson@example.com",
        phone: "+1234567892",
        role: "User",
        status: "Inactive",
    },
    {
        id: "4",
        first_name: "Sarah",
        last_name: "Wilson",
        email: "sarah.wilson@example.com",
        phone: "+1234567893",
        role: "Admin",
        status: "Active",
    },
    {
        id: "5",
        first_name: "David",
        last_name: "Brown",
        email: "david.brown@example.com",
        phone: "+1234567894",
        role: "User",
        status: "Active",
    },

    // 👇 20 more users
    {
        id: "6",
        first_name: "Emily",
        last_name: "Davis",
        email: "emily.davis@example.com",
        phone: "+1234567895",
        role: "User",
        status: "Inactive",
    },
    {
        id: "7",
        first_name: "Robert",
        last_name: "Miller",
        email: "robert.miller@example.com",
        phone: "+1234567896",
        role: "Admin",
        status: "Active",
    },
    {
        id: "8",
        first_name: "Olivia",
        last_name: "Taylor",
        email: "olivia.taylor@example.com",
        phone: "+1234567897",
        role: "User",
        status: "Active",
    },
    {
        id: "9",
        first_name: "William",
        last_name: "Anderson",
        email: "william.anderson@example.com",
        phone: "+1234567898",
        role: "User",
        status: "Inactive",
    },
    {
        id: "10",
        first_name: "Sophia",
        last_name: "Thomas",
        email: "sophia.thomas@example.com",
        phone: "+1234567899",
        role: "Admin",
        status: "Active",
    },
    {
        id: "11",
        first_name: "James",
        last_name: "Jackson",
        email: "james.jackson@example.com",
        phone: "+1234567800",
        role: "User",
        status: "Active",
    },
    {
        id: "12",
        first_name: "Isabella",
        last_name: "White",
        email: "isabella.white@example.com",
        phone: "+1234567801",
        role: "Admin",
        status: "Inactive",
    },
    {
        id: "13",
        first_name: "Benjamin",
        last_name: "Harris",
        email: "benjamin.harris@example.com",
        phone: "+1234567802",
        role: "User",
        status: "Active",
    },
    {
        id: "14",
        first_name: "Ava",
        last_name: "Martin",
        email: "ava.martin@example.com",
        phone: "+1234567803",
        role: "Admin",
        status: "Active",
    },
    {
        id: "15",
        first_name: "Lucas",
        last_name: "Thompson",
        email: "lucas.thompson@example.com",
        phone: "+1234567804",
        role: "User",
        status: "Inactive",
    },
    {
        id: "16",
        first_name: "Mia",
        last_name: "Garcia",
        email: "mia.garcia@example.com",
        phone: "+1234567805",
        role: "User",
        status: "Active",
    },
    {
        id: "17",
        first_name: "Henry",
        last_name: "Martinez",
        email: "henry.martinez@example.com",
        phone: "+1234567806",
        role: "Admin",
        status: "Active",
    },
    {
        id: "18",
        first_name: "Charlotte",
        last_name: "Robinson",
        email: "charlotte.robinson@example.com",
        phone: "+1234567807",
        role: "User",
        status: "Inactive",
    },
    {
        id: "19",
        first_name: "Alexander",
        last_name: "Clark",
        email: "alexander.clark@example.com",
        phone: "+1234567808",
        role: "Admin",
        status: "Active",
    },
    {
        id: "20",
        first_name: "Amelia",
        last_name: "Rodriguez",
        email: "amelia.rodriguez@example.com",
        phone: "+1234567809",
        role: "User",
        status: "Active",
    },
    {
        id: "21",
        first_name: "Daniel",
        last_name: "Lewis",
        email: "daniel.lewis@example.com",
        phone: "+1234567810",
        role: "Admin",
        status: "Inactive",
    },
    {
        id: "22",
        first_name: "Evelyn",
        last_name: "Lee",
        email: "evelyn.lee@example.com",
        phone: "+1234567811",
        role: "User",
        status: "Active",
    },
    {
        id: "23",
        first_name: "Matthew",
        last_name: "Walker",
        email: "matthew.walker@example.com",
        phone: "+1234567812",
        role: "Admin",
        status: "Active",
    },
    {
        id: "24",
        first_name: "Harper",
        last_name: "Hall",
        email: "harper.hall@example.com",
        phone: "+1234567813",
        role: "User",
        status: "Inactive",
    },
    {
        id: "25",
        first_name: "Logan",
        last_name: "Allen",
        email: "logan.allen@example.com",
        phone: "+1234567814",
        role: "User",
        status: "Active",
    },
];
